image: registry.gitlab.com/yakshaving.art/go-builder:0.0.2
stages:
  - build
  - release

build:
  stage: build
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  artifacts:
    paths:
    - propaganda
  script:
  - mkdir -p /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - cd /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - ln -s ${CI_PROJECT_DIR}
  - cd /go/src/gitlab.com/${CI_PROJECT_PATH}
  - make test build

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - ln -s Dockerfile.amd64 Dockerfile
    - docker build --cache-from $CONTAINER_IMAGE:latest
      --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA
      --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest

release_tag:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - ln -s Dockerfile.amd64 Dockerfile
    - docker build --cache-from $CONTAINER_IMAGE:latest
      --tag $CONTAINER_IMAGE:$CI_COMMIT_TAG
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_TAG
  only:
  - tags