image: registry.gitlab.com/yakshaving.art/go-builder:0.0.2
stages:
  - build
  - release

build:
  stage: build
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  cache:
    paths:
    - vendor
  artifacts:
    paths:
    - propaganda
  script:
  - mkdir -p /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - cd /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - ln -s ${CI_PROJECT_DIR}
  - cd /go/src/gitlab.com/${CI_PROJECT_PATH}
  - make test build

.build-image: &build-image
  stage: release
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - ln -s Dockerfile.amd64 Dockerfile
  after_script:
    - docker logout

build:
  <<: *build-image
  script:
    - docker build --cache-from ${CONTAINER_IMAGE}:latest
      --tag ${CONTAINER_IMAGE}:${CI_COMMIT_SHA}
      --tag ${CONTAINER_IMAGE}:latest .
  except:
  - master

release:
  <<: *build-image
  script:
    - docker build --cache-from ${CONTAINER_IMAGE}:latest
      --tag ${CONTAINER_IMAGE}:latest .
    - docker push ${CONTAINER_IMAGE}:${CI_COMMIT_SHA}
    - docker push ${CONTAINER_IMAGE}:latest
  only:
  - master

release_tag:
  <<: *build-docker
  script:
    - docker build --cache-from ${CONTAINER_IMAGE}:latest
      --tag ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}
  only:
  - tags