image: golang:1.10
stages:
  - build

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - mkdir -p /go/src/gitlab.com/yakshaving.art
  - cp -r /builds/yakshaving.art/propaganda /go/src/gitlab.com/yakshaving.art/
  - cd /go/src/gitlab.com/yakshaving.art/propaganda
  - dep ensure

build:
  stage: build
  script:
    - go build
    
# test:
#   stage: test
#   coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
#   script:
#     - go test -v -coverprofile=coverage.out $(go list ./... | grep -v '/vendor/') && go tool cover -func=coverage.out
