image: golang:1.10
stages:
  - test
  - build

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - mkdir -p /go/src/gitlab.com/yakshaving.art
  - cp -r /builds/yakshaving.art/propaganda /go/src/gitlab.com/yakshaving.art/
  - cd /go/src/gitlab.com/yakshaving.art/propaganda

test:
  stage: test
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  script:
  - make test

build:
  stage: build
  script:
  - make build
    